title: "Yiming's Mathematics Notes"
description: "Concise notes on selected topics in mathematics."
url: "https://yimingz89.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
      math: true

exclude:
  - README.md
